//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arm.Ad.Users
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ADUserDetail", Namespace="http://schemas.datacontract.org/2004/07/WcfCommonServices.AdHelper")]
    public partial class ADUserDetail : object
    {
        
        private string CityField;
        
        private string CompanyField;
        
        private string ContainerNameField;
        
        private string CountryField;
        
        private string DepartmentField;
        
        private string DisplayNameField;
        
        private string EmailAddressField;
        
        private string ExtensionField;
        
        private string FaxField;
        
        private string FirstNameField;
        
        private string HomePhoneField;
        
        private string LastNameField;
        
        private string LoginNameField;
        
        private string LoginNameWithDomainField;
        
        private string ManagerNameField;
        
        private string MiddleNameField;
        
        private string MobileField;
        
        private string NotesField;
        
        private string ObjectCategoryField;
        
        private string OfficeField;
        
        private string PostalCodeField;
        
        private string StateField;
        
        private string StreetAddressField;
        
        private string TitleField;
        
        private string UserControlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City
        {
            get
            {
                return this.CityField;
            }
            set
            {
                this.CityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company
        {
            get
            {
                return this.CompanyField;
            }
            set
            {
                this.CompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContainerName
        {
            get
            {
                return this.ContainerNameField;
            }
            set
            {
                this.ContainerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department
        {
            get
            {
                return this.DepartmentField;
            }
            set
            {
                this.DepartmentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone
        {
            get
            {
                return this.HomePhoneField;
            }
            set
            {
                this.HomePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName
        {
            get
            {
                return this.LoginNameField;
            }
            set
            {
                this.LoginNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginNameWithDomain
        {
            get
            {
                return this.LoginNameWithDomainField;
            }
            set
            {
                this.LoginNameWithDomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerName
        {
            get
            {
                return this.ManagerNameField;
            }
            set
            {
                this.ManagerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes
        {
            get
            {
                return this.NotesField;
            }
            set
            {
                this.NotesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectCategory
        {
            get
            {
                return this.ObjectCategoryField;
            }
            set
            {
                this.ObjectCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Office
        {
            get
            {
                return this.OfficeField;
            }
            set
            {
                this.OfficeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StreetAddress
        {
            get
            {
                return this.StreetAddressField;
            }
            set
            {
                this.StreetAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserControl
        {
            get
            {
                return this.UserControlField;
            }
            set
            {
                this.UserControlField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Arm.Ad.Users.ISOAPADHelperService")]
    public interface ISOAPADHelperService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/GetUserDepartment", ReplyAction="http://tempuri.org/ISOAPADHelperService/GetUserDepartmentResponse")]
        System.Threading.Tasks.Task<string> GetUserDepartmentAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/GetUsernameByEmailAddress", ReplyAction="http://tempuri.org/ISOAPADHelperService/GetUsernameByEmailAddressResponse")]
        System.Threading.Tasks.Task<string> GetUsernameByEmailAddressAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/AuthenticateUser", ReplyAction="http://tempuri.org/ISOAPADHelperService/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string emailAddress, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/GetUserByEmailAddress", ReplyAction="http://tempuri.org/ISOAPADHelperService/GetUserByEmailAddressResponse")]
        System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail> GetUserByEmailAddressAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/GetUsersInDepartment", ReplyAction="http://tempuri.org/ISOAPADHelperService/GetUsersInDepartmentResponse")]
        System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail[]> GetUsersInDepartmentAsync(string department, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/GetUsersFromGroup", ReplyAction="http://tempuri.org/ISOAPADHelperService/GetUsersFromGroupResponse")]
        System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail[]> GetUsersFromGroupAsync(string groupName, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/GetUserByDisplayName", ReplyAction="http://tempuri.org/ISOAPADHelperService/GetUserByDisplayNameResponse")]
        System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail> GetUserByDisplayNameAsync(string displayName, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/GetDisabledUsers", ReplyAction="http://tempuri.org/ISOAPADHelperService/GetDisabledUsersResponse")]
        System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail[]> GetDisabledUsersAsync(string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/CheckUserOrGroup", ReplyAction="http://tempuri.org/ISOAPADHelperService/CheckUserOrGroupResponse")]
        System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail> CheckUserOrGroupAsync(string searchQuery, string emailAddress);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPADHelperService/GetUsersBySearchQuery", ReplyAction="http://tempuri.org/ISOAPADHelperService/GetUsersBySearchQueryResponse")]
        System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail[]> GetUsersBySearchQueryAsync(string searchQuery, string emailAddress);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ISOAPADHelperServiceChannel : Arm.Ad.Users.ISOAPADHelperService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SOAPADHelperServiceClient : System.ServiceModel.ClientBase<Arm.Ad.Users.ISOAPADHelperService>, Arm.Ad.Users.ISOAPADHelperService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SOAPADHelperServiceClient() : 
                base(SOAPADHelperServiceClient.GetDefaultBinding(), SOAPADHelperServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISOAPADHelperService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPADHelperServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SOAPADHelperServiceClient.GetBindingForEndpoint(endpointConfiguration), SOAPADHelperServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPADHelperServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SOAPADHelperServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPADHelperServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SOAPADHelperServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SOAPADHelperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetUserDepartmentAsync(string emailAddress)
        {
            return base.Channel.GetUserDepartmentAsync(emailAddress);
        }
        
        public System.Threading.Tasks.Task<string> GetUsernameByEmailAddressAsync(string emailAddress)
        {
            return base.Channel.GetUsernameByEmailAddressAsync(emailAddress);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string emailAddress, string password)
        {
            return base.Channel.AuthenticateUserAsync(emailAddress, password);
        }
        
        public System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail> GetUserByEmailAddressAsync(string emailAddress)
        {
            return base.Channel.GetUserByEmailAddressAsync(emailAddress);
        }
        
        public System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail[]> GetUsersInDepartmentAsync(string department, string emailAddress)
        {
            return base.Channel.GetUsersInDepartmentAsync(department, emailAddress);
        }
        
        public System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail[]> GetUsersFromGroupAsync(string groupName, string emailAddress)
        {
            return base.Channel.GetUsersFromGroupAsync(groupName, emailAddress);
        }
        
        public System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail> GetUserByDisplayNameAsync(string displayName, string emailAddress)
        {
            return base.Channel.GetUserByDisplayNameAsync(displayName, emailAddress);
        }
        
        public System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail[]> GetDisabledUsersAsync(string emailAddress)
        {
            return base.Channel.GetDisabledUsersAsync(emailAddress);
        }
        
        public System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail> CheckUserOrGroupAsync(string searchQuery, string emailAddress)
        {
            return base.Channel.CheckUserOrGroupAsync(searchQuery, emailAddress);
        }
        
        public System.Threading.Tasks.Task<Arm.Ad.Users.ADUserDetail[]> GetUsersBySearchQueryAsync(string searchQuery, string emailAddress)
        {
            return base.Channel.GetUsersBySearchQueryAsync(searchQuery, emailAddress);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISOAPADHelperService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISOAPADHelperService))
            {
                return new System.ServiceModel.EndpointAddress("https://iamunavailable");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SOAPADHelperServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISOAPADHelperService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SOAPADHelperServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISOAPADHelperService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISOAPADHelperService,
        }
    }
}
