using Arm.GrcApi.Modules.Compliance.CompliancePlanning;
using GrcApi.Modules.Shared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace GrcApi.Modules.Compliance.CompliancePlanning
{
    public class ComplianceRegulatorConfiguration : IEntityTypeConfiguration<ComplianceRegulator>
    {
        public void Configure(EntityTypeBuilder<ComplianceRegulator> builder)
        {
            builder.Property(b => b.RegulatorTitle).IsRequired().HasMaxLength(500);
            builder.Property(b => b.Description).HasMaxLength(int.MaxValue);

            // Seed Regulators
            builder.HasData(
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.LABOURACT), "LABOUR ACT"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.PENSIONREFORMACT), "PENSION REFORM ACT 2004"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.COMPANIESANDALLIEDMATTERSACT), "COMPANIES AND ALLIED MATTERS ACT LFN 2004"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.COMPANIESINCOMETAXREGULATIONS), "COMPANIES INCOME TAX (RATE etc OF TAX DEDUCTED AT SOURCE (WITHOLDING TAX) REGULATIONS 1977"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.COMPANIESINCOMETAXACT), "COMPANIES INCOME TAX ACT LFN 2004"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.EMPLOYEESCOMPENSATIONACT), "EMPLOYEES COMPENSATION ACT"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.FINANCIALREPORTINNGCOUNCILOFNIGERIAACT), "FINANCIAL REPORTINNG COUNCIL OF NIGERIA ACT 2011"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.INVESTMENTANDSECURITIESACT), "INVESTMENT & SECURITIES ACT 2007"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.NATIONALYOUTHSERVICECORPSACT), "NATIONAL YOUTH SERVICE CORPS ACT"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.PAYASYOUEARN), "PAY AS YOU EARN (PAYE)"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.PERSONALINCOMETAXREGULATION), "PERSONAL INCOME TAX (RATE etc OF TAX DEDUCTED AT SOURCE (WITHHOLDING TAX REGULATION) 1997"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.PERSONALINCOMETAXACT), "PERSONAL INCOME TAX ACT LFN 2004"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.VALUEADDEDTAX), "VALUE ADDED TAX LFN 2004"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.CIRCULARONMINIMUMREQUIREMENTSFOROPENINGBRANCHES), "CIRCULAR ON MINIMUM REQUIREMENTS FOR OPENING BRANCHES"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.CIRCULARONPAYMENTOFACCRUEDPRE_PENSIONREFORMBENEFITS), "CIRCULAR ON PAYMENT OF ACCRUED PRE-PENSION REFORM BENEFITS MAY 2011"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.CIRCULARONREQUIREMENTSFORPFAsWITHFUNDSUNDERMANAGEMENTOFN100BILLION), "CIRCULAR ON REQUIREMENTS FOR PFAs WITH FUNDS UNDER MANAGEMENT OF N100 BILLION & ABOVE AND NEW REQUIREMENTS FOR APPOINTMENTS TO BOARD AND TOP MANAGEMENT POSITIONS OF ALL PFAs"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.CIRCULARONSERVICEDELIVERYBYPENSIONFUNDADMINISTRATORS), "CIRCULAR ON SERVICE DELIVERY BY PENSION FUND ADMINISTRATORS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.CIRCULARONSTANDARDIZATIONOFANNUALTOTALEMOLUMENTSFORTHECOMPUTATIONOFRETIREMENTBENEFITS), "CIRCULAR ON STANDARDIZATION OF ANNUAL TOTAL EMOLUMENTS FOR THE COMPUTATION OF RETIREMENT BENEFITS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.CIRCULARONTHEIMPORTANCEOFTRAININGFORSTAFFOFPENSIONFUNDOPERATORS), "CIRCULAR ON THE IMPORTANCE OF TRAINING FOR STAFF OF PENSION FUND OPERATORS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.CODEOFCORPORATEGOVERNANCE), "CODE OF CORPORATE GOVERNANCE"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.CODEOFETHICSANDBUSINESSPRACTICES), "CODE OF ETHICS & BUSINESS PRACTICES"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINEFORAPPOINTMENTTOBOARDANDTOPMANAGEMENTPOSITIONSINPFAsANDPFCs), "GUIDELINE FOR APPOINTMENT TO BOARD AND TOP MANAGEMENT POSITIONS IN PFAs AND PFCs"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORCROSSBOARDERARRANGEMENTSUNDERPENSIONREFORMACT), "GUIDELINES FOR CROSS BOARDER ARRANGEMENTS UNDER PENSION REFORM ACT"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORLIFEINSURANCEPOLICYFOREMPLOYEES), "GUIDELINES FOR LIFE INSURANCE POLICY FOR EMPLOYEES"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORRISKMANAGEMENTFRAMEWORKFORLICENSEDOPERATORS), "GUIDELINES FOR RISK MANAGEMENT FRAMEWORK FOR LICENSED OPERATORS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORTHEADMINISTRATIONOFSTATEFUNDSDEDUCTEDATSOURCEUNDERTHECONTRIBUTORYPENSIONSCHEME), "GUIDELINES FOR THE ADMINISTRATION OF STATE FUNDS DEDUCTED AT SOURCE UNDER THE CONTRIBUTORY PENSION SCHEME"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORTHEAPPOINTMENTOFPENSIONFUNDADMINISTRATORSANDCUSTODIANSFOREXISTINGPENSIONSCHEMES), "GUIDELINES FOR THE APPOINTMENT OF PENSION FUND ADMINISTRATORS AND CUSTODIANS FOR EXISTING PENSION SCHEMES"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORTHEAPPOINTMENTOFPENSIONFUNDCUSTODIANSFORSTATEGOVERNMENTANDRETIREEFUNDS), "GUIDELINES FOR THE APPOINTMENT OF PENSION FUND CUSTODIANS FOR STATE GOVERNMENT AND RETIREE FUNDS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORTHEOPERATIONSOFPENSIONFUNDCUSTODIANS), "GUIDELINES FOR THE OPERATIONS OF PENSION FUND CUSTODIANS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORTHEOPERATIONSOFPENSIONTRANSITIONALARRANGEMENTDEPARTMENTS), "GUIDELINES FOR THE OPERATIONS OF PENSION TRANSITIONAL ARRANGEMENT DEPARTMENTS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORTHEOPERATIONSOFPFAS), "GUIDELINES FOR THE OPERATIONS OF PFAS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORTHEPUBLICATIONOFRATESOFRETURNONRSAFUNDSBYPENSIONFUNDADMINISTRATORS), "GUIDELINES FOR THE PUBLICATION OF RATES OF RETURN ON RSA FUNDS BYPENSION FUND ADMINISTRATORS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORTHETRANSFEROFNSITFCONTRIBUTIONSINTOEMPLOYEESRETIREMENTSAVINGSACCOUNT), "GUIDELINES FOR THE TRANSFER OF NSITF CONTRIBUTIONS INTO EMPLOYEES RETIREMENT SAVINGS ACCOUNT"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESFORTRANSITIONALCONTRIBUTIONSFUND), "GUIDELINES FOR TRANSITIONAL CONTRIBUTIONS FUND"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESONDIRECTREALESTATEINVESTMENTSBYCLOSEDPENSIONFUNDADMINISTRATORSANDAPPROVEDEXISTINGSCHEMES), "GUIDELINES ON DIRECT REAL ESTATE INVESTMENTS BY CLOSED PENSION FUND ADMINISTRATORS AND APPROVED EXISTING SCHEMES"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.GUIDELINESONFUNDACCOUNTING), "GUIDELINES ON FUND ACCOUNTING"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.INCLUSIONOFGROUPLIFEINSURANCEPOLICYFOREMPLOYEESFURTHERSTEPSTOIMPROVECOMPLIANCE), "INCLUSION OF GROUP LIFE INSURANCE POLICY FOR EMPLOYEES: FURTHER STEPS TO IMPROVE COMPLIANCE"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.MINIMUMINFORMATIONTOBEPOSTEDONAPFAsWEBSITE), "MINIMUM INFORMATION TO BE POSTED ON A PFAs WEBSITE"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.REGULATIONONINVESTMENTOFPENSIONFUNDASSETS), "REGULATION ON INVESTMENT OF PENSION FUND ASSETS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.REGULATIONSFORAUDITINGPENSIONFUNDS), "REGULATIONS FOR AUDITING PENSION FUNDS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.REGULATIONSFORTHEADMINISTRATIONOFRETIREMENTANDTERMINALBENEFITS), "REGULATIONS FOR THE ADMINISTRATION OF RETIREMENT AND TERMINAL BENEFITS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.REGULATIONSONCOMPLIANCEOFFICERS), "REGULATIONS ON COMPLIANCE OFFICERS"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.SECURITIESANDEXCHANGECOMMISSIONRULESANDREGULATIONS), "SECURITIES AND EXCHANGE COMMISSION RULES AND REGULATIONS 2013"),
                ComplianceRegulator.Create(new Guid(ComplianceRegulatorSeedGuids.WHISTLEBLOWINGGUIDELINESFORPENSIONS), "WHISTLE BLOWING GUIDELINES FOR PENSIONS")
            );
        }
    }
}
