namespace Arm.GrcApi.Modules.IncidentManagement
{
    /*
       * Original Author: Sodiq Quadre
       * Date Created: 04/04/2025
       * Development Group: GRCTools
       * Incidence management Options    
       */
    public class IncidenceMgtOptionsEndpoint
    {
        public static async Task<IResult> HandleAsync()
        {
            var Status = new string[] { "Open", "Work In Progress", "Closed" };
            var SecurityAreas = new string[] { "Confidentiality", "Integrity", "Availability" };
            var Severity = new string[] { "Low", "Medium", "High" };                  
            var TypeOfAsset = new string[] { "Hardware :- Servers, Laptops, Desktops, Mobile Devices, Network Switches, Routers, Firewalls, IoT Devices, Printers, USB Drives", "Software :- Operating Systems, Business Applications, Virtual Machines, Databases, Antivirus, CRM, ERP Systems, Development Tools", "Database :- SQL Databases (MySQL, MSSQL, Oracle), NoSQL Databases (MongoDB), Cloud Databases (AWS RDS, Firebase)", "Data :- Customer PII, Financial Data, Intellectual Property, Employee Records, Encryption Keys, Backups", "Network :- LAN, WAN, VPN, Firewalls, IDS/IPS, Proxies, Load Balancers, Wireless Networks, DNS Servers, VoIP Systems", "Cloud :- SaaS (Google Workspace, O365), PaaS (AWS Lambda), IaaS (AWS, Azure, GCP), Cloud Storage (S3, Google Drive)", "Physical security :- CCTV Cameras, Biometric Access Systems, Smart Locks, RFID Keycards, Security Alarms, Motion Sensors", "Human :- Employees, Contractors, Consultants, Third-Party Vendors, Privileged Users (Admins, Developers, Executives)", "Thirdparty and Supply Chain assets :- Vendor Systems, Managed Security Services, Cloud Service Providers, Open Source Dependencies, Payment Processors", "IOT and Embedded systems :- Smart Cameras, Industrial Control Systems (ICS), Smart Sensors, Wearables, Connected Vehicles", "Communication and Collaboration tools :- Email Systems, Microsoft Teams, Zoom, Slack, VOIP Systems, Instant Messaging Apps", "Identity and Access Management systems :- Active Directory, Single Sign-On (SSO), Multi-Factor Authentication (MFA), Privileged Access Management (PAM)", "Backup and Recovery systems :- Backup Servers, Cloud Backup Solutions, Disaster Recovery (DR) Systems, Tape Backups", "Development & CI/CD Pipelines :- Git Repositories (GitHub, GitLab), Jenkins, Docker Containers, Kubernetes, API Gateways", "AI :- AI Chatbots, Machine Learning Models, AI-powered Analytics, AI-based Fraud Detection Systems, LLMs (Large Language Models)" };
            var Impact = new string[] { "Hardware :- Cost of replacement, revenue loss, business disruption, loss of customer trust, possible compliance fines", "Software :- Cost of remediation, service unavailability, customer dissatisfaction, legal fines", "Database :- Data recovery costs, data loss, service disruptions, erosion of trust, breach notification obligations", "Data :- Cost of remediation, lawsuits, loss of sensitive data, brand damage, customer churn, regulatory violations", "Network :- Revenue loss from downtime, network outages, service unavailability, data privacy violations", "Cloud :- Cost of security enhancements, loss of cloud services, customer distrust, cloud provider liability issues", "Physical Security :- Replacement costs, security vulnerabilities, loss of trust, potential compliance breaches", "Human :- Fraud-related losses, loss of productivity, customer confidence erosion, insider threat liability", "Third-Party & Supply Chain Assets :- Compensation to customers, dependency on external providers, loss of partner trust, breach of contractual agreements", "IoT & Embedded Systems :- High mitigation costs, service disruptions, risk to customer privacy, non-compliance with IoT security regulations", "Communication & Collaboration Tools :- Business email compromise losses, breakdown in communication, loss of trust in internal security, data protection law violations", "Identity & Access Management (IAM) Systems :- Data recovery expenses, loss of control over critical assets, perceived weak security controls, regulatory fines", "Backup & Recovery Systems :- Data restoration costs, inability to recover lost data, reduced confidence in recovery capabilities, compliance violations", "Development & CI/CD Pipelines :- Business disruptions, introduction of security flaws, product integrity concerns, intellectual property theft risks", "AI Assets :- Impacted business decisions, incorrect AI predictions, ethical concerns, violations of AI transparency regulations" };
            var IncidenceTag = new string[] { "False Positive", "True Positive" };
            return TypedResults.Ok(new { Status, SecurityAreas, Severity, TypeOfAsset, Impact, IncidenceTag });

        }
    }
}
